CONTAINER Opointcloudobject
{
	NAME Opointcloudobject;
	INCLUDE Obase;

	GROUP ID_OBJECTPROPERTIES
	{
		FILENAME POINTCLOUDOBJECT_FILE { ANIM OFF; }
		BUTTON POINTCLOUDOBJECT_LOADBTN { ANIM OFF; }
		BOOL POINTCLOUDOBJECT_INVERTY	{ ANIM OFF; }
		REAL POINTCLOUDOBJECT_POINTSIZE	 { UNIT REAL; MIN 0.0; MINEX; ANIM OFF; STEP 0.1;	 }
		REAL POINTCLOUDOBJECT_DENSITY	 { UNIT PERCENT; CUSTOMGUI REALSLIDER; MINSLIDER 0.001; MIN 0.0; MINEX; MAX 100.0; ANIM OFF; }
	}
}
